[package]
name = "minichain-vm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Register-based virtual machine for minichain"

[dependencies]
minichain-core.workspace = true
thiserror.workspace = true
serde.workspace = true
